---
- name: "Create groups"
  group:
    name: "{{ item.group }}"
  with_items: "{{ user_groups }}"
  tags:
    - groupadd
    - users

- name: "Set sudo rights for groups"
  template:
    src: groups-sudoers.j2
    dest: '/etc/sudoers.d/{{ item.group }}-group-sudoers'
    owner: root
    group: root
    mode: 0400
  with_items: '{{ user_groups }}'
  when: item.sudo is defined
  tags:
    - groupadd
    - sudo
    - users

- name: "Create users"
  user:
    name:             '{{ item.name }}'
    comment:          '{{ item.comment          | default(omit) }}'
    shell:            '{{ item.shell            | default("/bin/bash") }}'
    createhome:       '{{ item.createhome       | default("yes") }}'
    home:             '{{ item.home             | default(omit) }}'
    password:         '{{ item.password         | default(omit) }}'
    update_password:  '{{ item.update_password  | default(omit) }}'
    expires:          '{{ item.expires          | default(omit) }}'
    system:           '{{ item.system           | default("no") }}'
    generate_ssh_key: '{{ item.generate_ssh_key | default("no") }}'
  with_items: '{{ users }}'
  tags:
    - useradd
    - ssh
    - users

- name: "Add users to groups"
  user:
    name:   '{{ item.name }}'
    group:  '{{ item.group  | default(omit) }}'
    groups: '{{ item.groups | default(omit) }}'
    append: '{{ item.append | default("yes") }}'
  with_items: '{{ users }}'
  when: (item.group is defined) or (item.groups is defined)
  tags:
    - useradd
    - ssh
    - users

- name: "Authorize users to login via ssh"
  authorized_key:
    user: '{{ item.name }}'
    key:  '{{ item.key }}'
  with_items: '{{ users }}'
  when: item.key is defined
  tags:
    - useradd
    - ssh
    - users

- name: "Remove users"
  user:
    name:  '{{ item }}'
    state: absent
    force: yes
  with_items: '{{ removed_users }}'
  tags:
    - userdel
    - ssh
    - users

- name: "Remove groups"
  user:
    name: '{{ item.group }}'
    state: absent
    force: yes
  with_items: '{{ removed_user_groups }}'
  tags:
    - groupdel
    - users

- name: "Remove sudo file"
  file:
    name: '/etc/sudoers.d/{{ item.group }}-group-sudoers'
    state: absent
  with_items: '{{ removed_user_groups }}'
  tags:
    - groupdel
    - users
